Updated sysdeps, compiler tools. Added at_panic procedure.

diff --git a/ada-bind b/ada-bind
--- a/ada-bind
+++ b/ada-bind
@@ -1,28 +1,50 @@
 #!/bin/sh
 
+fatal()
+{
+  echo "ada-bind: fatal: $1" 1>&2
+  exit 1
+}
+
 if [ $# -lt 1 ]
 then
-  echo "usage: source" 1>&2
+  echo "ada-bind: usage: [@dir] source" 1>&2
   exit 1
 fi
+
+#
+# check if new base dir was specified
+#
+
+BASE_DIR="."
+if [ $# -eq 2 ]
+then
+  BASE_DIR=`echo "$1" | sed 's/^@//g'`
+  shift
+fi
+
+#
+# Extract base name of given source file.
+#
+
+out=`echo "$1" | awk -F. '{print $1}'`
+src="$1"
+shift
 
 ADABIND=`head -n 1 conf-adabind`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-adabind" 1>&2
-  exit 1
+  fatal "could not read conf-adabind"
 fi
 SYSTYPE=`head -n 1 conf-systype`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-systype" 1>&2
-  exit 1
+  fatal "could not read conf-systype"
 fi
 ADATYPE=`head -n 1 conf-adatype`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-adatype" 1>&2
-  exit 1
+  fatal "could not read conf-adatype"
 fi
 
 ADAFLAGS="${ADAFLAGS} `head -n 1 conf-adabflags 2>/dev/null`"
@@ -35,18 +57,10 @@ if [ -f "conf-adafflist" ]
 then
   for f in `cat "conf-adafflist"`
   do
-    FLAGS=`cat $f 2>/dev/null`
+    FLAGS=`cat $f 2>/dev/null` || fatal "could not read $f"
     ADAFLAGS="${ADAFLAGS} ${FLAGS}"
   done
 fi
-
-#
-# Extract base name of given source file.
-#
-
-out=`echo "$1" | awk -F. '{print $1}'`
-src="$1"
-shift
 
 #
 # Read local flag file list, if present.
@@ -57,7 +71,7 @@ then
   for f in `cat "${out}.iff"`
   do
     targ="`dirname $out`/`dirname $f`/`basename $f`"
-    FLAGS="`cat $targ 2>/dev/null`"
+    FLAGS="`cat $targ 2>/dev/null`" || fatal "could not read $f"
     ADAFLAGS="${ADAFLAGS} ${FLAGS}"
   done
 fi
diff --git a/ada-compile b/ada-compile
--- a/ada-compile
+++ b/ada-compile
@@ -1,43 +1,26 @@
 #!/bin/sh
 
+fatal()
+{
+  echo "ada-compile: fatal: $1" 1>&2
+  exit 1
+}
+
 if [ $# -lt 1 ]
 then
-  echo "usage: source" 1>&2
+  echo "ada-compile: usage: [@dir] source" 1>&2
   exit 1
 fi
-
-ADA=`head -n 1 conf-adacomp`
-if [ $? -ne 0 ]
-then
-  echo "fatal: could not read conf-adacomp" 1>&2
-  exit 1
-fi
-SYSTYPE=`head -n 1 conf-systype`
-if [ $? -ne 0 ]
-then
-  echo "fatal: could not read conf-systype" 1>&2
-  exit 1
-fi
-ADATYPE=`head -n 1 conf-adatype`
-if [ $? -ne 0 ]
-then
-  echo "fatal: could not read conf-adatype" 1>&2
-  exit 1
-fi
-
-ADAFLAGS="${ADAFLAGS} `head -n 1 conf-adacflags 2>/dev/null`"
 
 #
-# Read global flag file list, if present.
+# check if new base dir was specified
 #
 
-if [ -f "conf-adafflist" ]
+BASE_DIR="."
+if [ $# -eq 2 ]
 then
-  for f in `cat "conf-adafflist"`
-  do
-    FLAGS=`cat $f 2>/dev/null`
-    ADAFLAGS="${ADAFLAGS} ${FLAGS}"
-  done
+  BASE_DIR=`echo "$1" | sed 's/^@//g'`
+  shift
 fi
 
 #
@@ -48,6 +31,37 @@ out=`echo "$1" | awk -F. '{print $1}'`
 src="$1"
 shift
 
+ADA=`head -n 1 "${BASE_DIR}/conf-adacomp"`
+if [ $? -ne 0 ]
+then
+  fatal "could not read ${BASE_DIR}/conf-adacomp"
+fi
+SYSTYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
+if [ $? -ne 0 ]
+then
+  fatal "could not read ${BASE_DIR}/conf-systype"
+fi
+ADATYPE=`head -n 1 "${BASE_DIR}/conf-adatype"`
+if [ $? -ne 0 ]
+then
+  fatal "could not read ${BASE_DIR}/conf-adatype"
+fi
+
+ADAFLAGS="${ADAFLAGS} `head -n 1 ${BASE_DIR}/conf-adacflags 2>/dev/null`"
+
+#
+# Read global flag file list, if present.
+#
+
+if [ -f "${BASE_DIR}/conf-adafflist" ]
+then
+  for f in `cat "${BASE_DIR}/conf-adafflist"`
+  do
+    FLAGS=`cat $f 2>/dev/null` || fatal "could not read $f"
+    ADAFLAGS="${ADAFLAGS} ${FLAGS}"
+  done
+fi
+
 #
 # Read local flag file list, if present.
 #
@@ -56,8 +70,8 @@ if [ -f "${out}.iff" ]
 then
   for f in `cat "${out}.iff"`
   do
-    targ="`dirname $out`/`dirname $f`/`basename $f`"
-    FLAGS="`cat $targ 2>/dev/null`"
+    targ="`dirname $out`/`dirname $f`/`basename $f`" 
+    FLAGS="`cat $targ 2>/dev/null`" || fatal "could not read $f"
     ADAFLAGS="${ADAFLAGS} ${FLAGS}"
   done
 fi
diff --git a/ada-srcmap b/ada-srcmap
--- a/ada-srcmap
+++ b/ada-srcmap
@@ -2,7 +2,7 @@
 
 fatal()
 {
-  echo "fatal: $1" 1>&2
+  echo "ada-srcmap: fatal: $1" 1>&2
   exit 1
 }
 
@@ -34,13 +34,25 @@ EOF
 
 if [ $# -lt 1 ]
 then
-  echo "usage: file.apk" 1>&2
+  echo "ada-srcmap: usage: [@dir] file.apk" 1>&2
   exit 1
 fi
 
-ADA=`head -n 1 conf-adacomp` || fatal "could not read conf-adacomp"
-SYSTYPE=`head -n 1 conf-systype` || fatal "could not read conf-systype"
-ADATYPE=`head -n 1 conf-adatype` || fatal "could not read conf-adatype"
+#
+# check if base directory was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
+then
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
+fi
+
+ADA=`head -n 1 ${BASE_DIR}/conf-adacomp` || fatal "could not read ${BASE_DIR}/conf-adacomp"
+SYSTYPE=`head -n 1 ${BASE_DIR}/conf-systype` || fatal "could not read ${BASE_DIR}/conf-systype"
+ADATYPE=`head -n 1 ${BASE_DIR}/conf-adatype` || fatal "could not read ${BASE_DIR}/conf-adatype"
 
 pkg=`head -n 1 "$1" | awk '{print $1}'` || fatal "could not read package name"
 spec=`head -n 1 "$1" | awk '{print $2}'` || fatal "could not read package spec"
diff --git a/ada-srcmap-all b/ada-srcmap-all
--- a/ada-srcmap-all
+++ b/ada-srcmap-all
@@ -2,7 +2,7 @@
 
 fatal()
 {
-  echo "fatal: $1" 1>&2
+  echo "ada-srcmap-all: fatal: $1" 1>&2
   exit 1
 }
 
@@ -13,9 +13,21 @@ make_map()
   ./ada-srcmap "$1"
 }
 
-ADA=`head -n 1 conf-adacomp` || fatal "could not read conf-adacomp"
-SYSTYPE=`head -n 1 conf-systype` || fatal "could not read conf-systype"
-ADATYPE=`head -n 1 conf-adatype` || fatal "could not read conf-adatype"
+#
+# check if base directory was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
+then
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
+fi
+
+ADA=`head -n 1 ${BASE_DIR}/conf-adacomp` || fatal "could not read ${BASE_DIR}/conf-adacomp"
+SYSTYPE=`head -n 1 ${BASE_DIR}/conf-systype` || fatal "could not read ${BASE_DIR}/conf-systype"
+ADATYPE=`head -n 1 ${BASE_DIR}/conf-adatype` || fatal "could not read ${BASE_DIR}/conf-adatype"
 
 case $ADATYPE in
   GCC)
@@ -27,9 +39,9 @@ case $ADATYPE in
     ;;
 esac
 
-if [ -f conf-mkfdirs ]
+if [ -f ${BASE_DIR}/conf-mkfdirs ]
 then
-  DIRS=`cat conf-mkfdirs` || fatal "could not read conf-mkfdirs"
+  DIRS=`cat ${BASE_DIR}/conf-mkfdirs` || fatal "could not read ${BASE_DIR}/conf-mkfdirs"
 fi
 DIRS=". ${DIRS}"
 
diff --git a/cc-compile b/cc-compile
--- a/cc-compile
+++ b/cc-compile
@@ -1,71 +1,30 @@
 #!/bin/sh
 
+fatal()
+{
+  echo "cc-compile: fatal: $1" 1>&2
+  exit 1
+}
+
 if [ $# -lt 1 ]
 then
-  echo "usage: source" 1>&2
+  echo "cc-compile: usage: [@dir] source" 1>&2
   exit 1
 fi
 
 #
-# Assume source is being cross compiled if there is a cross-compiler
-# defined.
+# check if new base dir was specified
 #
 
-if [ -f conf-x-cc ]
+BASE_DIR="."
+if [ $# -gt 1 ]
 then
-  CC=`head -n 1 conf-x-cc`
-  if [ $? -ne 0 ]
+  echo "$1" | grep '^@' >/dev/null
+  if [ $? -eq 0 ]
   then
-    echo "fatal: could not read conf-x-cc" 1>&2
-    exit 1
+    BASE_DIR=`echo "$1" | sed 's/^@//g'`
+    shift
   fi
-  SYSTYPE=`head -n 1 conf-x-systype`
-  if [ $? -ne 0 ]
-  then
-    echo "fatal: could not read conf-x-systype" 1>&2
-    exit 1
-  fi
-  CCTYPE=`head -n 1 conf-x-cctype`
-  if [ $? -ne 0 ]
-  then
-    echo "fatal: could not read conf-x-cctype" 1>&2
-    exit 1
-  fi
-  CFLAGS="${CFLAGS} `head -n 1 conf-x-cflags 2>/dev/null`"
-else
-  CC=`head -n 1 conf-cc`
-  if [ $? -ne 0 ]
-  then
-    echo "fatal: could not read conf-cc" 1>&2
-    exit 1
-  fi
-  SYSTYPE=`head -n 1 conf-systype`
-  if [ $? -ne 0 ]
-  then
-    echo "fatal: could not read conf-systype" 1>&2
-    exit 1
-  fi
-  CCTYPE=`head -n 1 conf-cctype`
-  if [ $? -ne 0 ]
-  then
-    echo "fatal: could not read conf-cctype" 1>&2
-    exit 1
-  fi
-fi
-
-CFLAGS="${CFLAGS} `head -n 1 conf-cflags 2>/dev/null`"
-
-#
-# Read global flag file list, if present.
-#
-
-if [ -f "conf-ccfflist" ]
-then
-  for f in `cat "conf-ccfflist"`
-  do
-    FLAGS=`cat $f 2>/dev/null`
-    CFLAGS="${CFLAGS} ${FLAGS}"
-  done
 fi
 
 #
@@ -75,6 +34,62 @@ fi
 out=`echo "$1" | awk -F. '{print $1}'`
 src="$1"
 shift
+
+#
+# Assume source is being cross compiled if there is a cross-compiler
+# defined.
+#
+
+if [ -f "${BASE_DIR}/conf-x-cc" ]
+then
+  CC=`head -n 1 "${BASE_DIR}/conf-x-cc"`
+  if [ $? -ne 0 ]
+  then
+    fatal "could not read ${BASE_DIR}/conf-x-cc"
+  fi
+  SYSTYPE=`head -n 1 "${BASE_DIR}/conf-x-systype"`
+  if [ $? -ne 0 ]
+  then
+    fatal "could not read ${BASE_DIR}/conf-x-systype"
+  fi
+  CCTYPE=`head -n 1 "${BASE_DIR}/conf-x-cctype"`
+  if [ $? -ne 0 ]
+  then
+    fatal "could not read ${BASE_DIR}/conf-x-cctype"
+  fi
+  CFLAGS="${CFLAGS} `head -n 1 "${BASE_DIR}/conf-x-cflags" 2>/dev/null`"
+else
+  CC=`head -n 1 "${BASE_DIR}/conf-cc"`
+  if [ $? -ne 0 ]
+  then
+    fatal "could not read ${BASE_DIR}/conf-cc"
+  fi
+  SYSTYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
+  if [ $? -ne 0 ]
+  then
+    fatal "could not read ${BASE_DIR}/conf-systype"
+  fi
+  CCTYPE=`head -n 1 "${BASE_DIR}/conf-cctype"`
+  if [ $? -ne 0 ]
+  then
+    fatal "could not read ${BASE_DIR}/conf-cctype"
+  fi
+fi
+
+CFLAGS="${CFLAGS} `head -n 1 ${BASE_DIR}/conf-cflags 2>/dev/null`"
+
+#
+# Read global flag file list, if present.
+#
+
+if [ -f "${BASE_DIR}/conf-ccfflist" ]
+then
+  for f in `cat "${BASE_DIR}/conf-ccfflist"`
+  do
+    FLAGS=`cat $f 2>/dev/null`
+    CFLAGS="${CFLAGS} ${FLAGS}"
+  done
+fi
 
 #
 # Read local flag file list, if present.
diff --git a/cc-link b/cc-link
--- a/cc-link
+++ b/cc-link
@@ -1,9 +1,27 @@
 #!/bin/sh
 
+fatal()
+{
+  echo "cc-link: fatal: $1" 1>&2
+  exit 1
+}
+
 if [ $# -lt 2 ]
 then
-  echo "usage: basename objects ..." 1>&2
+  echo "cc-link: usage: [@dir] basename objects ..." 1>&2
   exit 1
+fi
+
+#
+# check if base directory was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
+then
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
 fi
 
 #
@@ -11,57 +29,51 @@ fi
 # defined.
 #
 
-if [ -f conf-x-ld ]
+if [ -f "${BASE_DIR}/conf-x-ld" ]
 then
-  LD=`head -n 1 conf-x-ld`
+  LD=`head -n 1 "${BASE_DIR}/conf-x-ld"`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-x-ld" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-x-ld"
   fi
-  SYSTYPE=`head -n 1 conf-x-systype`
+  SYSTYPE=`head -n 1 "${BASE_DIR}/conf-x-systype"`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-x-systype" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-x-systype"
   fi  
-  LDTYPE=`head -n 1 conf-x-ldtype`
+  LDTYPE=`head -n 1 "${BASE_DIR}/conf-x-ldtype"`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-x-ldtype" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-x-ldtype"
   fi
-  LDFLAGS="${LDFLAGS} `head -n 1 conf-x-ldflags 2>/dev/null`"
+  LDFLAGS="${LDFLAGS} `head -n 1 ${BASE_DIR}/conf-x-ldflags 2>/dev/null`"
 else
-  LD=`head -n 1 conf-ld`
+  LD=`head -n 1 "${BASE_DIR}/conf-ld"`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-ld" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-ld"
   fi
-  SYSTYPE=`head -n 1 conf-systype`
+  SYSTYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-systype" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-systype"
   fi  
-  LDTYPE=`head -n 1 conf-ldtype`
+  LDTYPE=`head -n 1 "${BASE_DIR}/conf-ldtype"`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-ldtype" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-ldtype"
   fi
 fi
 
-LDFLAGS="${LDFLAGS} `head -n 1 conf-ldflags 2>/dev/null`"
+LDFLAGS="${LDFLAGS} `head -n 1 ${BASE_DIR}/conf-ldflags 2>/dev/null`"
 
 #
 # Read global flag file list, if present.
 #
 
-if [ -f "conf-ldfflist" ]
+if [ -f "${BASE_DIR}/conf-ldfflist" ]
 then
-  for f in `cat "conf-ldfflist"`
+  for f in `cat "${BASE_DIR}/conf-ldfflist"`
   do
     FLAGS=`cat $f 2>/dev/null`
     LDFLAGS="${LDFLAGS} ${FLAGS}"
diff --git a/cc-slib b/cc-slib
--- a/cc-slib
+++ b/cc-slib
@@ -1,37 +1,52 @@
 #!/bin/sh
 
+fatal()
+{
+  echo "cc-slib: fatal: $1" 1>&2
+  exit 1
+}
+
 if [ $# -lt 2 ]
 then
-  echo "usage: basename objects ..." 1>&2
+  echo "cc-slib: usage: [@dir] basename objects ..." 1>&2
   exit 1
 fi
 
-SYS_TYPE=`head -n 1 conf-systype`
+#
+# check if base directory was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
+then
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
+fi
+
+SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-systype" 1>&2
-  exit 1
+  fatal "could not read ${BASE_DIR}/conf-systype"
 fi
 
 AR="ar cr"
-if [ -f conf-ar ]
+if [ -f "${BASE_DIR}/conf-ar" ]
 then
-  AR=`head -n 1 conf-ar`
+  AR=`head -n 1 "${BASE_DIR}/conf-ar"`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-ar" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-ar"
   fi
 fi
 
 RANLIB="ranlib"
-if [ -f conf-ranlib ]
+if [ -f ${BASE_DIR}/conf-ranlib ]
 then
-  RANLIB=`head -n 1 conf-ranlib`
+  RANLIB=`head -n 1 ${BASE_DIR}/conf-ranlib`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-ranlib" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-ranlib"
   fi
 fi
 
diff --git a/mk-adatype b/mk-adatype
--- a/mk-adatype
+++ b/mk-adatype
@@ -1,5 +1,12 @@
 #!/bin/sh
 
+fatal()
+{
+  echo "mk-adatype: fatal: $1" 1>&2
+  cleanup
+  exit 1
+}
+
 cleanup()
 {
   rm -f
@@ -15,11 +22,22 @@ try_v()
   return 1
 }
 
-SYS_ADA=`head -n 1 conf-adacomp`
+#
+# check if base directory was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
+then
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
+fi
+
+SYS_ADA=`head -n 1 ${BASE_DIR}/conf-adacomp`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-adacomp" 1>&2
-  exit 1
+  fatal "could not read ${BASE_DIR}/conf-adacomp"
 fi
 
 # try V output
@@ -30,6 +48,4 @@ then
   exit 0
 fi
 
-echo "fatal: could not determine ada compiler type"
-cleanup
-exit 1
+fatal "could not determine ada compiler type"
diff --git a/mk-cctype b/mk-cctype
--- a/mk-cctype
+++ b/mk-cctype
@@ -2,13 +2,32 @@
 
 cleanup()
 {
-  rm -f _mk_cctype.c _mk_cctype
+  rm -f _mk_cctype.c _mk_cctype _mk_cctype.exe
 }
 
-SYS_CC=`head -n 1 conf-cc`
+fatal()
+{
+  echo "mk-cctype: fatal: $1" 1>&2
+  cleanup
+  exit 1
+}
+
+#
+# check if base directory was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
+then
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
+fi
+
+SYS_CC=`head -n 1 ${BASE_DIR}/conf-cc`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-cc" 1>&2
+  fatal "could not read ${BASE_DIR}/conf-cc"
   exit 1
 fi
 
@@ -18,12 +37,12 @@ fi
 # this system.
 #
 
-if [ -f conf-x-cctype ]
+if [ -f ${BASE_DIR}/conf-x-cctype ]
 then
-  TYPE=`head -n 1 conf-x-cctype`
+  TYPE=`head -n 1 ${BASE_DIR}/conf-x-cctype`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-x-cctype" 1>&2
+    fatal "could not read ${BASE_DIR}/conf-x-cctype"
     cleanup
     exit 1
   fi
@@ -186,23 +205,17 @@ EOF
 ) > _mk_cctype.c
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not create _mk_cctype.c" 1>&2
-    cleanup
-    exit 1
+    fatal "could not create _mk_cctype.c"
   fi
   ${SYS_CC} -o _mk_cctype _mk_cctype.c
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not create _mk_cctype" 1>&2
-    cleanup
-    exit 1
+    fatal "could not create _mk_cctype"
   fi
-  ./_mk_cctype
+  ./_mk_cctype | tr -cd '[[:alnum:]_\n]'
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not execute _mk_cctype" 1>&2
-    cleanup
-    exit 1
+    fatal "could not execute _mk_cctype"
   fi
 fi
 
diff --git a/mk-ldtype b/mk-ldtype
--- a/mk-ldtype
+++ b/mk-ldtype
@@ -1,18 +1,30 @@
 #!/bin/sh
 
-if [ -f conf-x-cctype ]
+#
+# check if base directory was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
 then
-  CC_TYPE=`head -n 1 conf-x-cctype`
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
+fi
+
+if [ -f "${BASE_DIR}/conf-x-cctype" ]
+then
+  CC_TYPE=`head -n 1 "${BASE_DIR}/conf-x-cctype"`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-x-cctype" 1>&2
+    echo "fatal: could not read ${BASE_DIR}/conf-x-cctype" 1>&2
     exit 1
   fi
 else
-  CC_TYPE=`head -n 1 conf-cctype`
+  CC_TYPE=`head -n 1 "${BASE_DIR}/conf-cctype"`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-cctype" 1>&2
+    echo "fatal: could not read ${BASE_DIR}/conf-cctype" 1>&2
     exit 1
   fi
 fi
diff --git a/mk-mk-ctxt b/mk-mk-ctxt
--- a/mk-mk-ctxt
+++ b/mk-mk-ctxt
@@ -1,14 +1,41 @@
 #!/bin/sh
-# $Id$
 
-CC=`head -n 1 conf-cc`
-if [ $? -ne 0 ]
-then
-  echo "fatal: could not read conf-cc" 1>&2
+fatal()
+{
+  echo "mk-mk-ctxt: fatal: $1" 1>&2
   exit 1
+}
+
+cleanup()
+{
+  rm -f mk-ctxt.c mk-ctxt.o
+}
+
+#
+# check if base directory was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
+then
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
 fi
 
-cat > mk-ctxt.c << EOF
+CC=`head -n 1 ${BASE_DIR}/conf-cc`
+if [ $? -ne 0 ]
+then
+  fatal "could not read ${BASE_DIR}/conf-cc"
+fi
+
+LD=`head -n 1 ${BASE_DIR}/conf-ld`
+if [ $? -ne 0 ]
+then
+  fatal "could not read ${BASE_DIR}/conf-ld"
+fi
+
+(cat << EOF
 #include <stdio.h>
 #include <unistd.h>
 
@@ -58,7 +85,8 @@ int main(int argc, char **argv)
   return 0;
 }
 EOF
+) > mk-ctxt.c || fatal "could not create mk-ctxt.c"
 
-${CC} -c -o mk-ctxt.o mk-ctxt.c
-${CC} -o mk-ctxt mk-ctxt.o
-rm -f mk-ctxt.c mk-ctxt.o
+${CC} -c -o mk-ctxt.o mk-ctxt.c || fatal "could not compile mk-ctxt.c"
+${LD} -o mk-ctxt mk-ctxt.o      || fatal "could not link mk-ctxt"
+cleanup
diff --git a/mk-sosuffix b/mk-sosuffix
--- a/mk-sosuffix
+++ b/mk-sosuffix
@@ -1,11 +1,27 @@
 #!/bin/sh
-# $Id$
 
-SYS_TYPE=`head -n 1 conf-systype`
+fatal()
+{
+  echo "mk-sosuffix: fatal: $1" 1>&2
+  exit 1
+}
+
+#
+# check if base directory was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
+then
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
+fi
+
+SYS_TYPE=`head -n 1 "${BASE_DIR}/conf-systype"`
 if [ $? -ne 0 ]
 then
-  echo "fatal: could not read conf-systype" 1>&2
-  exit 1
+  fatal "could not read ${BASE_DIR}/conf-systype"
 fi
 
 case "${SYS_TYPE}" in
diff --git a/mk-systype b/mk-systype
--- a/mk-systype
+++ b/mk-systype
@@ -1,25 +1,47 @@
 #!/bin/sh
-# $Id$
+
+fatal()
+{
+  echo "mk-systype: fatal: $1" 1>&2
+  cleanup
+  exit 1
+}
 
 cleanup()
 {
-  rm -f _mk_systype.c _mk_systype
+  rm -f _mk_systype.c _mk_systype _mk_systype.exe
 }
 
-SYS_CC=`head -n 1 conf-cc`
-if [ $? -ne 0 ]
+#
+# check if base directory was specified
+#
+
+BASE_DIR="."
+echo "$1" | grep '^@' 2>&1 >/dev/null
+if [ $? -eq 0 ]
 then
-  echo "fatal: could not read conf-cc" 1>&2
-  exit 1
+  BASE_DIR=`echo $1 | sed 's/^@//g'`
+  shift
 fi
 
-if [ -f conf-x-systype ]
+SYS_CC=`head -n 1 ${BASE_DIR}/conf-cc`
+if [ $? -ne 0 ]
 then
-  SYS=`head -n 1 conf-x-systype`
+  fatal "could not read ${BASE_DIR}/conf-cc"
+fi
+
+SYS_LD=`head -n 1 ${BASE_DIR}/conf-ld`
+if [ $? -ne 0 ]
+then
+  fatal "could not read ${BASE_DIR}/conf-ld"
+fi
+
+if [ -f "${BASE_DIR}/conf-x-systype" ]
+then
+  SYS=`head -n 1 "${BASE_DIR}/conf-x-systype"`
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not read conf-x-systype" 1>&2
-    exit 1
+    fatal "could not read ${BASE_DIR}/conf-x-systype"
   fi
   echo "${SYS}"
 else
@@ -143,23 +165,17 @@ EOF
 ) > _mk_systype.c
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not create _mk_systype.c" 1>&2
-    cleanup
-    exit 1
+    fatal "could not create _mk_systype.c"
   fi
-  ${SYS_CC} -o _mk_systype _mk_systype.c
+  ${SYS_LD} -o _mk_systype _mk_systype.c
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not create _mk_systype" 1>&2
-    cleanup
-    exit 1
+    fatal "could not create _mk_systype"
   fi
-  ./_mk_systype
+  ./_mk_systype | tr -cd '[[:alnum:]_\n]'
   if [ $? -ne 0 ]
   then
-    echo "fatal: could not execute _mk_systype" 1>&2
-    cleanup
-    exit 1
+    fatal "could not execute _mk_systype"
   fi
 fi
 
