Build errors are friendly

diff --git a/check-deps b/check-deps
--- a/check-deps
+++ b/check-deps
@@ -1,11 +1,23 @@
 #!/bin/sh
 
 EXIT_VALUE=0
+PROGRAM_NAME="check-deps"
+
 
 fatal()
 {
-  echo "check-deps: fatal: $1" 1>&2
+  echo "${PROGRAM_NAME}: fatal: $1" 1>&2
   exit 1
+}
+
+error()
+{
+  echo "${PROGRAM_NAME}: error: $1" 1>&2
+}
+
+info()
+{
+  echo "${PROGRAM_NAME}: info: $1" 1>&2
 }
 
 require_fail()
@@ -15,8 +27,8 @@ require_fail()
   MODULE_NAME="$3"
   FILE_NAME="$4"
 
-  echo "check-deps: error: ${PACKAGE_NAME} (${PACKAGE_URL}) required but not located" 1>&2
-  echo "check-deps: error: SYSDEPS module ${MODULE_NAME}, file ${FILE_NAME}" 1>&2
+  error "${PACKAGE_NAME} (${PACKAGE_URL}) required but not located" 1>&2
+  error "SYSDEPS module ${MODULE_NAME}, file ${FILE_NAME}" 1>&2
 
   EXIT_VALUE=1
 }
@@ -39,5 +51,11 @@ cd SYSDEPS || fatal "could not change directory to SYSDEPS"
 
 required lua-flags  flags-lua  "Lua"
 required lua-libs-S libs-lua-S "Lua"
+
+if [ ${EXIT_VALUE} -ne 0 ]
+then
+  info "See the documentation on SYSDEPS if you do not understand how to fix this problem"
+  info "http://coreland.ath.cx/code/sysdeps"
+fi
 
 exit ${EXIT_VALUE}
